FROM golang:1.22.4-alpine3.20 as build

ENV CI=true \
    CGO_ENABLED=0 \
    GO111MODULE=on

WORKDIR /app

ADD . .

RUN apk add --no-cache git && \
    go install -v github.com/go-task/task/v3/cmd/task@latest && \
    task build -f

FROM alpine:3.15

COPY --from=build /app/build/package /

COPY config.yaml /opt/opsgin/config.yaml

ENTRYPOINT ["/usr/local/sbin/opsgin"]
