FROM golang:1.23-alpine3.20 AS build

ENV CI=true \
    CGO_ENABLED=0 \
    GO111MODULE=on

WORKDIR /app

ADD . .

RUN apk add --no-cache git && \
    go mod download && \
    go build -o /usr/local/sbin/opsgin

FROM alpine:3.15

COPY --from=build /usr/local/sbin/opsgin /usr/local/sbin/opsgin

COPY config.yaml /opt/opsgin/config.yaml

ENTRYPOINT ["/usr/local/sbin/opsgin"]
